Model ACE_B6_N7_17_07_rid_1.2_rep, Test RSS
Test run at 2020-08-21 10:26

model file: ../../models/ACE_B6_N7_17_07_rid_1.2_rep/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 108, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/ACE_B6_N7_17_07_rid_1.2_rep/model.py'
